"use client";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.css";
import "./globals.css";
import BootstrapActivation from "@/helpers/BootstrapActivation";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { AccountContext, IAccountInfo } from "@/context/AccountContext";
import { useState } from "react";

/*
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
*/

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [accountInfo, setAccountInfo] = useState<IAccountInfo | undefined>();

	const updateAccountInfo = (value: IAccountInfo) => {
		setAccountInfo(value);
		localStorage.setItem("_jwt", value.jwt!);
		localStorage.setItem("_refreshToken", value.refreshToken ?? "");
	};

	return (
		<html lang="en">
			<body>
				<AccountContext.Provider
					value={{
						accountInfo: accountInfo,
						setAccountInfo: updateAccountInfo,
					}}
				>
					<Header />
					{/* {accountInfo?.jwt} */}
					<div className="container">
						<main role="main" className="pb-3">
							{children}
						</main>
					</div>

					<Footer />
					<BootstrapActivation />
				</AccountContext.Provider>
			</body>
		</html>
	);
}
